name: Unit Tests

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    unit_tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.3', '7.4', '8.0', '8.1']

        name: PHP ${{ matrix.php-versions }} Tests

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v1"

            -   run: vendor/bin/phpunit